### ISSUE TITLE
Can we have the GAN part code?

### ISSUE THREAD

**Issue by wangjiyuan9** [astra-vision/rain-rendering#20]

**Comment by wangjiyuan9** [comment]
Thank you for your contribution! However, I noticed that GANs also play an important role in the rendering process according to the paper I read. I tried to look for the relevant code, but was unable to find it. Would it be possible for you to open-source it?

**Comment by rdecharette** [comment]
Hello @wangjiyuan9,

Sorry I don't have the GAN code readily accessible, however, it's a standard CycleGAN trained on nuScenes clear to rain. Splits are obtained using a simple "rain" word search in each frame metadata. The remaining details are in the paper.
<img src="https://user-images.githubusercontent.com/5967026/217782239-7c9370b0-4720-443c-935f-4c5ba1f39796.png" width="50%">
The only "trick" I remember is that some supposedly "rain" frames are mis-annotated. So you'll need to curate the rain split and remove frames obviously non-rainy. A rough curation is sufficient.

The whole process is quite easy. Good luck.

**Comment by wangjiyuan9** [comment]
Thanks a lot!



At 2023-02-09 18:16:36, "Raoul de Charette" ***@***.***> wrote:

Hello @wangjiyuan9,

Sorry I don't have the GAN code readily accessible, however, it's a standard CycleGAN trained on nuScenes clear to rain. Splits are obtained using a simple "rain" word search in each frame metadata. The remaining details are in the paper.

The only "trick" I remember is that some supposedly "rain" frames are mis-annotated. So you'll need to curate the rain split and remove frames obviously non-rainy. A rough curation is sufficient.

The whole process is quite easy. Good luck.

**Comment by wangjiyuan9** [comment]
Hello!
I don't find any "weather" attribution. How did you "using a simple "rain" word search in each frame metadata"?
the metadata of nuScence are:
```
log - Log information from which the data was extracted.
scene - 20 second snippet of a car's journey.
sample - An annotated snapshot of a scene at a particular timestamp.
sample_data - Data collected from a particular sensor.
ego_pose - Ego vehicle poses at a particular timestamp.
sensor - A specific sensor type.
calibrated sensor - Definition of a particular sensor as calibrated on a particular vehicle.
instance - Enumeration of all object instance we observed.
category - Taxonomy of object categories (e.g. vehicle, human).
attribute - Property of an instance that can change while the category remains the same.
visibility - Fraction of pixels visible in all the images collected from 6 different cameras.
sample_annotation - An annotated instance of an object within our interest.
map - Map data that is stored as binary semantic masks from a top-down view.
```
Thanks for you help!

**Comment by rdecharette** [comment]
btw, you can check https://www.nuscenes.org/tutorials/nuscenes_tutorial.html#A-look-at-the-dataset which shows example of the "description" field.

**Comment by wangjiyuan9** [comment]
Thanks!
