### ISSUE TITLE
Pretrained GAN 

### ISSUE THREAD

**Issue by ravikothari510** [astra-vision/rain-rendering#27]
Hi,
As per the paper it seems you have also used CycleGan to generate base rain images and later applied PBR pipeline. Is there a plan to release the GAN weights too, as it seems the image quality with the joint rendering looks better as compared to simulating rain streaks.

**Comment by rdecharette** [comment]
Hi,
https://github.com/astra-vision/rain-rendering/issues/20#issuecomment-1423944781
