### ISSUE TITLE
 Download issue

### ISSUE THREAD

**Issue by ElhamIsmail** [astra-vision/rain-rendering#30]
I am currently facing an issue while downloading both depth maps and the pre-computed KITTI particles simulation. Could you please  update the links?

**Comment by rdecharette** [comment]
Hi @ElhamIsmail,

Inria is currently moving to a new location which is why all our servers are shutdown during the moving. As far as I understand they should be reconnected in 1 or 2 weeks. Sorry about that.

Best

**Comment by ElhamIsmail** [comment]
Thanks alot
